version: '3'
services:
    db:
      image: mysql:latest
      volumes:
        - ./wp_data:/var/lib/mysql
      restart: always
      ports:
        - 3306:3306
      env-file:
        - .env
      environment:
        MYSQL_ROOT_PASSWORD: IekAdsela42!!
        MYSQL_DATABASE: backend_ahrenshoop
        MYSQL_USER: ba_ah
        MYSQL_PASSWORD: 2grobi6

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      volumes: 
        - ./wp_content:/var/www/html/wp-content/
      ports:
        - "80:80"
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
        WORDPRESS_DB_USER: ${MYSQL_USER}
        WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
volumes:
    db_data: